pyreader/pyreader/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pyreader.views.home', name='home'),
    # url(r'^pyreader/', include('pyreader.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'',include('pyreader_site.urls',namespace='pyreader')),
    url(r'^admin/', include(admin.site.urls)),
)

pyreader/pyreader_site/urls.py
from django.conf.urls import url,patterns,include

from pyreader_site import views

urlpatterns=patterns('',
    	url(r'^$',views.index,name='index'),
        url(r'^index_page/$',views.page_index,name='page_index'),
    	url(r'^test/$',views.test,name='test'),
    	url(r'^accounts/login/$',views.login_view,name='login'),
    	url(r'^accounts/register/$',views.register,name='register'),
    	url(r'^accounts/logout/$',views.logout_view,name='logout'),
        url(r'^channels/$',views.show_channels,name='show_channels'),
		url(r'^channels/create/$',views.create_channel,name='create_channel'),
		url(r'^channels/check_create_channel/$',views.check_create_channel,name='check_create_channel'),
    	url(r'^channels/(?P<channel_id>\d+)/$',views.channel_details,name='channel_details'),
	)

pyreader/pyreader_site/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth import get_user_model


class RssChannel(models.Model):
	link=models.CharField(max_length=255,unique=True)
	title=models.CharField(max_length=256,blank=False)
	description=models.CharField(max_length=2048,blank=True)
	creation_date=models.DateTimeField("creation date",default=timezone.now())
	last_update=models.DateTimeField("last update date",default=timezone.now())
	language=models.CharField(max_length=32,default='en')
	copyright=models.CharField(max_length=1024,blank=True)
	#time to live in minutes
	ttl=models.IntegerField(default=30)

	def __unicode__(self):
		return self.title

	class Meta:
		db_table='rss_channels'

class RssItem(models.Model):
	title=models.CharField(max_length=255)
	description=models.CharField(max_length=8096)
	link=models.CharField(max_length=512)
	guid=models.CharField(max_length=512,blank=True)
	pubDate=models.DateTimeField('publication date',default=timezone.now())

	rssChannel=models.ForeignKey(RssChannel)

	class Meta:
		db_table='rss_items'


class ChannelTag(models.Model):
	tag_name=models.CharField(max_length=512,default='default tag name')
	creation_date=models.DateTimeField("tag creation date",default=timezone.now())
	tag_type=models.CharField(max_length=128,default='default tag type')

	def __unicode__(self):
		return self.tag_name

	class Meta:
		db_table='channel_tags'



class Subscription(models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL)
	channel=models.ForeignKey('Channel')
	subs_date=models.DateTimeField('subscription date',default=timezone.now())
	last_update=models.DateTimeField('last subscriprion update',default=timezone.now())

	class Meta:
		db_table='channel_subscription'

class Channel(models.Model):
	title=models.CharField(max_length=255,unique=True)
	ctype=models.CharField(max_length=128,default='public') #private,public
	#specifies who created this channel(user,admin,machine)
	creation_type=models.CharField(max_length=128,default='admin')
	is_category_channel=models.BooleanField(default=False)
	description=models.CharField(max_length=512,blank=True)
	creation_date=models.DateTimeField("creation date",default=timezone.now())
	last_update=models.DateTimeField("last channel update date",default=timezone.now())

	users=models.ManyToManyField(settings.AUTH_USER_MODEL,through='Subscription')
	tags=models.ManyToManyField(ChannelTag)
	rss_channels=models.ManyToManyField(RssChannel)
	sub_channels=models.ManyToManyField('self',symmetrical=False)

	def __unicode__(self):
		return "%s"%(self.title)

	class Meta:
		db_table='channels'

pyreader/pyreader_site/views.py
#TODO: rss_content design
#TODO: popular channels .. 
#TODO: sources of information

from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.http import HttpResponse,HttpResponseRedirect
from django.template import Context,loader,RequestContext
from django.shortcuts import render,get_object_or_404,render_to_response
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import generic
from django import forms
from django.db import transaction,IntegrityError
from django.contrib.auth import authenticate,login,logout
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils import simplejson
from django.core.cache import get_cache

import re

from pyreader_site.models import *
from pyreader_site.rss_handler import Rss_Handler

rss_handler=Rss_Handler()

# public_user=User.objects.get(username="public_channels")

class LoginForm(forms.Form):
	username=forms.CharField(max_length=256)
	password=forms.CharField(max_length=512)

class ChannelForm(forms.Form):
	name=forms.CharField(max_length=256)
	creation_date=timezone.now()

class RegisterForm(forms.Form):
	username=forms.CharField(max_length=256)
	email=forms.CharField(max_length=256)
	password=forms.CharField(max_length=256)

def get_channel_by_type(channel_id,ctype,user):
	try:
		if ctype=='public':
			return Channel.objects.get(pk=channel_id,ctype=ctype)
		elif not user.is_authenticated():
			return None
		else: return Channel.objects.get(pk=channel_id,users__id=user.id)
	except Channel.DoesNotExist:
		return None

def get_public_categories_with_channels():
	cache=get_cache('default')
	categories=cache.get('categories:public_categories',None)
	if categories==None:
		public_categories=Category.objects.filter(ctype='public').order_by('-last_update')
		categories=[]
		for index in range(len(public_categories)):
			pub_cat=public_categories[index]
			category={'id':index,'name':pub_cat.name,
					  'channels':pub_cat.channels.all().order_by('-last_update')}
			categories.append(category)
		cache.add('categories:public_categories',categories,300)

	return categories


def get_public_categories(request):
	return get_public_categories_with_channels()

def get_public_and_private_categories(request):
	categories=get_public_categories_with_channels()
	cache=get_cache('default')
	user_channels=cache.get('categories:'+request.user.username+'_category',None)
	if user_channels==None:
		user_channels=Channel.objects.filter(users=request.user.id).all().order_by('-last_update')
		cache.add('categories:'+request.user.username+'_category',user_channels)
	categories.append({'id':len(categories),'name':'my channels','channels':user_channels})
	return categories

@transaction.autocommit
def index(request):

	if not request.user.is_authenticated():
		categories=get_public_categories(request)
	else: categories=get_public_and_private_categories(request)
	
	if not 'req' in request.GET or not request.GET['req']=='true':
		return render (request,'index.html',{'login_required':False,'categories':categories,
		                					 'channel':None,'rss_content':None})

	if not 'channel_id' in request.GET or not 'ctype' in request.GET:
		return render (request,'index.html',{'login_required':False,'categories':categories,
		                					 'channel':None,'rss_content':None})

	try:
		channel_id=int(request.GET['channel_id'])
		ctype=request.GET['ctype']
	except ValueError:
		return render (request,'index.html',{'login_required':False,'categories':categories,
		                					 'channel':None,'rss_content':None})

	channel=get_channel_by_type(channel_id,ctype,request.user)
	if channel==None:
		return render(request,'index.html',{'login_required':False,'categories':categories,
				                		 	'channel':None,'rss_content':None})

	cache=get_cache('default')
	if ctype=='public':
		rss_content_key='rss:ch_id'+str(channel_id)
	else: rss_content_key='rss:ch_id'+str(channel_id)+'_'+request.user.username
	rss_content=cache.get(rss_content_key,None)
	if rss_content==None:
		#TODO: cachge, to a more flexible variant, where rss can be mixed using some algorithm
		#how many objects should i cache??
		rss_content=Rss_Content.objects.filter(rss_url__in=Rss_Url.objects.filter(channel=channel_id))[0:100]
		cache.add(rss_content_key,rss_content)

	# just a little stub, will be deleted in future. 
	if(len(rss_content)==0):
		rss_handler=Rss_Handler()
		urls=RssChannel.objects.filter(channel__id=channel_id)
		rss_content=[]
		for rss_urls in urls:
			feed=rss_handler.get_feed(rss_urls.url)
			rss_content+=feed
			for record in feed:
				rc=RssItem(title=record['title'],
						description=record['summary'],link=record['link'])
				rss_urls.rssitem_set.add(rc)
			rss_urls.save()
	return render(request,'index.html',	{'login_required':False,'categories':categories,
				 						 'channel':channel,'rss_content':rss_content[0:10]})
@csrf_exempt
def page_index(request):
	if not request.method=='POST':
		return HttpResponseRedirect('/')
	page_size=10
	max_page=10
	channel_id=request.POST['channel_id']
	elements=request.POST['elements']
	ctype=request.POST['ctype'].strip()
	try:
		channel_id=int(channel_id)
		elements=int(elements)
	except ValueError:
		return render(request,'stub_page.html')
	if channel_id<=0:
		return render(request,'stub_page.html')
	if elements<=0:
		elements=0
	 #if mod!=0 we on the last page
	elif elements%page_size!=0:
		return HttpResponse(simplejson.dumps([]),mimetype='application/javascript')
	page=elements/page_size+1
	#TODO: change in future to a more appropriate solution
	if page>=max_page:
		return HttpResponse(simplejson.dumps([]),mimetype='application/javascript')
	if ctype=='public':
		rss_content_key='rss:ch_id'+str(channel_id)
	else: rss_content_key='rss:ch_id'+str(channel_id)+'_'+request.user.username

	cache=get_cache('default')
	rss_content=cache.get(rss_content_key,None)
	if rss_content==None:
		#take away to the function
		if ctype=='public':
			rss_content=Rss_Content.objects.filter(rss_url__in=Rss_Url.objects.filter(channel=channel_id,channel__ctype=ctype))[0:100]
		elif request.user.is_authenticated():
			rss_content=Rss_Content.objects.filter(rss_url__in=Rss_Url.objects.filter(channel=channel_id,channel__users__id=request.user.id))[0:100]
		else:
			return HttpResponse(simplejson.dumps(out_data),mimetype='application/javascript')

	paginator=Paginator(rss_content,page_size)

	try:
		rss_data=paginator.page(page).object_list
		out_data=[]
		for d in rss_data:
			out_data.append({'title':d.title,'summary':d.summary})
	except PageNotAnInteger:
		out_data=[]
	except EmptyPage:
		out_data=[]
	return HttpResponse(simplejson.dumps(out_data),mimetype='application/javascript')

@transaction.autocommit
def login_view(request):
	if request.user.is_authenticated():
		return render(request,'accounts/register.html',
						{'error_message':'please, logout to login under a user',
						 'allow_login':'False'})
	if request.method == 'POST':
		form=LoginForm(request.POST)
		if form.is_valid():
			user=authenticate(username=form.cleaned_data['username'],
							  password=form.cleaned_data['password'])
			if user is None:
				form=LoginForm()
				return render(request,'login.html',{'error_message':'user none','form':form})
			elif not user.is_active:
				form=LoginForm()
				return render(request,'login.html',{'error_message':'user not active','form':form})
			else:
				login(request,user)
				return HttpResponseRedirect('/')
		else: 
			form=LoginForm()
			return render(request,'login.html',{'error_message':'invalid input data','form':form})
	elif request.method == 'GET':
		form=LoginForm()
		return render(request,'accounts/login.html',{'form':form})

@login_required(login_url='/accounts/login/')
def logout_view(request):
	logout(request)
	return HttpResponseRedirect('/')


def register(request):
	if request.user.is_authenticated():
		return render(request,'accounts/register.html',
						{'error_message':'please, logout to register a new user',
						 'allow_registration':'False'})
	if request.method=='POST':
		form=RegisterForm(request.POST)
		if form.is_valid():
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']
			email=form.cleaned_data['email']
			if(User.objects.filter(username=username)):
				form=RegisterForm()
				return render(request,'register.html',
					{'error_message':'user with this email already exists',
					'form':form,'allow_registration':'True'})
			User.objects.create_user(username,email,password)
			user=authenticate(username=username,password=password)
			login(request,user)
			return HttpResponseRedirect('/')
	else:
		form=RegisterForm()
		return render(request,'accounts/register.html',
			{'form':form,'allow_registration':'True'})


@login_required(login_url='/accounts/login/')
def create_channel(request):
	if request.method == 'POST':
		form=ChannelForm(request.POST)
		if form.is_valid():
			channel_name=form.cleaned_data['name']
			creation_date=form.creation_date
			last_update_date=creation_date
			ch=Channel(name=channel_name,creation_date=creation_date,
					   last_channel_update_date=last_update_date)
			ch.user=request.user
			ch.save()
			return HttpResponseRedirect('/channel/show/')
	elif request.method=='GET':
		form=ChannelForm()
		return render(request,'channels/create_channel.html',{'form':form})

@transaction.autocommit
@login_required(login_url='/accounts/login/')
def show_channels(request):
	user=request.user
	user_channels=user.channel_set.all().order_by('-last_update')
	return render(request,'channels/show_channels.html',{'channels':user_channels})

@transaction.autocommit
@login_required(login_url='/accounts/login/')
def check_create_channel(request):
	if not request.method=='POST':
		return render(request,'channels/create_channel.html',{'form':ChannelForm()})
	user=request.user

pyreader/pyreader_site/templates/channels/channel_details.html
{% extends "base_form.html" %}

{% block title %} Simple channel template  {% endblock %}

{% block content%}
	
	<div class="channel_details">
		{{channel.name}}
	</div>

	<div class="rss_urls">
		{% for rss_url in rss_urls %}
			<p><label>url:  {{rss_url.url}}</label></p>
		{% endfor %}	
	</div>
	<p>
	<div id="rss_feeds">
		{%for feed in feeds%}
			<div id="rss_feed">
				<p>
				<div class="rss_feed_title">{{feed.title}}</div>
				</p>
				<p>
				<div class="rss_feed_content">{{feed.summary}}</div>
				</p>
			</div>
		{%endfor%}
	</div>
	</p>

{% endblock %}

pyreader/pyreader_site/templates/channels/create_channel.html
{% extends "base_form.html" %}

{% block title %} Create channel page {% endblock %}

{% block scripts %} 
<script type="text/javascript">

var current_label=4;
var allow_submit=true;

$(function(){

	$("#plus_rss_url").click(function(event){

		$("#rss_urls").append("<p><label for=\""+current_label+"\">url:</label><input id=\""+current_label+"\" onchange=\"validate(this.value,"+current_label+")\" type=\"text\" name=\"rss_url_"+current_label+"\"/> <label id=\"l"+current_label+"\"  class=\"error_message\" style=\"display: none;\"> * incorrect url</label> </p>");
		current_label+=1;

	});

	$('#channel_create').submit(function(){
		var valid=true;
		if(!$("input#id_name").val()) {
			valid=false;
			$("div#errors p#channel_name").show();
		}
		if($("label.error_message").is(":visible")){
			valid=false;
			$("div#errors p#incorrect_urls").show();
		}
		if(!valid){
			return false;
		}
	});

	$("#rss_urls input").focusout(function(event){
		
	});	

});

function validate(url,label_index){
		var isValid=validate_url(url.trim());
		if(isValid){
			$("label#l"+label_index).hide();
		}
		else{
			$("label#l"+label_index).show();
		}
}

function validate_url (url) {
		var url_pattern=new RegExp("^(\\w+\\.\\w+)((\\.\\w+)|(/\\w*)){0,}(\\?(\\w+=\\w+\&?){0,}){0,}$");
		if(!url){
			return true;
		}
		if(url.indexOf("://")!=-1){
			url=url.split("://")[1];
		}
		var isValid=url_pattern.test(url);
		return isValid;
	}

</script>
{% endblock %}


{% block content%}
	
	{%if error_messages %}
		<ul>
		{%for message in error_messages%}
			<li>{{message}}</li>
		{%endfor%}
		</ul>
	{%endif%}

	{{request.user.username}}
	<p/>
	<div id="errors">
		<br/><p class="error_message" id="incorrect_urls">* You have incorrect urls, please correct them.</p>
		<br/><p class="error_message" id="channel_name">* Enter the channel name please</p>
	</div>
	<form action="/channels/check_create_channel/" id="channel_create" method="post">{% csrf_token %}
		{%for field in form%}
			<div class="fieldWrapper">
				{{field.errors}}
				{{field.label_tag}}: {{field}}
			</div>
		{%endfor%}
		<div id="rss_urls" class="rss_urls_container">
			{%for index in "123" %}
				<p> <label for="{{index}}">url:</label>
					<input id="{{index}}"
					 type="text" name="{{"rss_url_"|add:index}}" onchange="validate(this.value,{{index}})"/> 
					<label id="l{{index}}" class="error_message"> * incorrect url</label>
				</p>
			{%endfor%}
		</div>
		<p><input type="button" id="plus_rss_url" value="+"/></p>
		<p><input type="submit" value="Submit" onsubmit="create_channel"/></p>
	</form>


{% endblock %}

pyreader/pyreader_site/templates/channels/show_channels.html
{% extends "base_form.html" %}

{% block title %} Channels  {% endblock %}

{% block content%}
	
	<div class="show_channels">

		{%if channels|length == 0%}
			<p> You do not have channels yet, but you can <a href="/channels/create/">CREATE</a> them!</p>
		{%else%}
			{%for channel in channels%}
				<p>
				<div class="show_channel">
					<a href="{%url 'pyreader:channel_details' channel.id%}">{{channel.name}}</a>
				</div>
				</p>
			{%endfor%}
		{%endif%}

	</div>

{% endblock %}